name: Build simple-service
on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    env: 
      DOCKER_REPOSITORY_NAME: sh777
      DOCKER_IMAGE_NAME: simple-service
      DOCKER_TAG_PREFIX: 1.4.

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login Docker Registry
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USERNAME }}
          password: ${{ secrets.DOCKER_REGISTRY_PASSWORD }}

      - uses: docker/setup-buildx-action@v1
        id: buildx
        with:
          install: true

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{env.DOCKER_REPOSITORY_NAME}}/${{env.DOCKER_IMAGE_NAME}}
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=sha,prefix={{branch}}-
            type=raw,${{ steps.extract-tag.outputs.result }}
          flavor: |
            latest=true
            prefix=${{ env.DOCKER_TAG_PREFIX }}          

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          file: ./Dockerfile
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: ${{ steps.meta.outputs.images }}:latest
          cache-to: type=inline

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{env.DOCKER_REPOSITORY_NAME}}/${{env.DOCKER_IMAGE_NAME}}:latest'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'